[package]
name = "kirjat-rs-api"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
env_logger = "0.9.1"
actix-cors = "0.6.3"
serde = "1"
anyhow = "1"
kirjat-rs = { version = "0.2.0", default_features = false, features = [ ] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false