[package]
name = "kirjat-rs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kirjat-rs = { git = "ssh://git@github.com/xypine/kirjat-rs.git", version = "0.2" }
actix-web = "4"
env_logger = "0.9.1"
actix-cors = "0.6.3"
serde = "1"
anyhow = "1"
